version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: revcycle_db
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: J8!rX9kP2@zQ4sT7
      POSTGRES_DB: revcycle_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: