version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: revcycle_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: revcycle_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker

  web:
    build: ./frontend
    container_name: revcycle_web
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  postgres_data: