# Variáveis para reutilizar nos testes
@host = http://localhost:3000
@email = contato@guilhermeborba.com.br
@password = forteSenha123

# =======================================================
#                  FLUXO DE AUTENTICAÇÃO
# =======================================================

### 1. Registrar um novo usuário (Opcional, se precisar de um novo)
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 2. Fazer Login
# @name loginRequest
POST {{host}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 3. Acessar Rota Protegida (Perfil)
# Usa o token direto da resposta do login
GET {{host}}/auth/profile
Authorization: Bearer {{loginRequest.response.body.access_token}}
Accept: application/json


# =======================================================
#               CRUD - REVENUE CYCLES
# =======================================================

### 4. Criar um novo Ciclo de Receita
# @name createCycleRequest
POST {{host}}/revenue-cycles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

{
  "patientId": "PATIENT-002",
  "payer": "Global Health Inc.",
  "procedureCode": "PROC-54321",
  "amount": 250.75,
  "stage": "PRE_AUTH",
  "claimStatus": "OPEN",
  "dueDate": "2025-10-15",
  "notes": "Pre-authorization request."
}


### 5. Listar todos os Ciclos de Receita
GET {{host}}/revenue-cycles
Authorization: Bearer {{loginRequest.response.body.access_token}}
Accept: application/json


### 6. Buscar o Ciclo de Receita recém-criado
GET {{host}}/revenue-cycles/{{createCycleRequest.response.body.id}}
Authorization: Bearer {{loginRequest.response.body.access_token}}
Accept: application/json


### 7. Atualizar o Ciclo de Receita
PATCH {{host}}/revenue-cycles/{{createCycleRequest.response.body.id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

{
  "claimStatus": "APPROVED",
  "notes": "Pre-authorization approved by Global Health Inc."
}


### 8. Deletar o Ciclo de Receita
DELETE {{host}}/revenue-cycles/{{createCycleRequest.response.body.id}}
Authorization: Bearer {{loginRequest.response.body.access_token}}


### 9. (TESTE DE FALHA) Tentar buscar o Ciclo deletado
# Esta requisição deve retornar um erro 404 Not Found
GET {{host}}/revenue-cycles/{{createCycleRequest.response.body.id}}
Authorization: Bearer {{loginRequest.response.body.access_token}}
Accept: application/json